-- back-end/db/schema.sql  (MySQL / MariaDB)
CREATE TABLE IF NOT EXISTS User (
  userId INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  zipcode VARCHAR(20) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Car (
  carId INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  year INT NOT NULL,
  model VARCHAR(255) NOT NULL,
  style VARCHAR(255),
  fuelType VARCHAR(255),
  mileage INT DEFAULT 0,
  make VARCHAR(255) NOT NULL,
  scheduled TEXT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(userId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ServiceProvider (
  providerId INT PRIMARY KEY AUTO_INCREMENT,
  provider VARCHAR(255) NOT NULL UNIQUE,
  priceRange VARCHAR(255),
  rating FLOAT,
  location VARCHAR(255),
  userAdded INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ServiceLog (
  logId INT PRIMARY KEY AUTO_INCREMENT,
  carId INT NOT NULL,
  userId INT NOT NULL,
  serviceId VARCHAR(255) NOT NULL,
  serviceName VARCHAR(255) NOT NULL,
  category VARCHAR(255),
  mileageAt INT NOT NULL,
  date VARCHAR(255) NOT NULL,
  costMin INT,
  costMax INT,
  notes TEXT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (carId) REFERENCES Car(carId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Review (
  reviewId INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  providerId INT,
  mechanicName VARCHAR(255) NOT NULL,
  rating INT NOT NULL,
  comment TEXT NOT NULL,
  jobType VARCHAR(255),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(userId) ON DELETE CASCADE,
  FOREIGN KEY (providerId) REFERENCES ServiceProvider(providerId) ON DELETE SET NULL
);

ALTER TABLE Review ADD UNIQUE KEY uniq_user_provider (userId, providerId);